import { PERMISSION_LIST, PERMISSIONS } from "./permissions";
import { ROLES } from "./roles";
import type { PermissionMap, RolePermission } from "./types";

export const ROLE_PERMISSION_MAP = {
  [ROLES.SUPER_ADMIN]: PERMISSION_LIST,
  [ROLES.ADMIN]: PERMISSION_LIST.filter((permission) => permission !== PERMISSIONS.TANGO_SYNC),
  [ROLES.SALES_SUPERVISOR]: [PERMISSIONS.CLIENTS_VIEW, PERMISSIONS.CLIENTS_CREATE, PERMISSIONS.CLIENTS_UPDATE, PERMISSIONS.PRODUCTS_VIEW, PERMISSIONS.PRODUCTS_CREATE, PERMISSIONS.PRODUCTS_UPDATE, PERMISSIONS.QUOTES_VIEW, PERMISSIONS.QUOTES_CREATE, PERMISSIONS.QUOTES_UPDATE, PERMISSIONS.QUOTES_CONVERT, PERMISSIONS.ORDERS_VIEW, PERMISSIONS.ORDERS_CREATE, PERMISSIONS.ORDERS_UPDATE, PERMISSIONS.ORDERS_APPROVE, PERMISSIONS.ORDERS_CANCEL, PERMISSIONS.DISCOUNTS_APPLY, PERMISSIONS.DISCOUNTS_OVERRIDE, PERMISSIONS.APPROVALS_VIEW, PERMISSIONS.APPROVALS_APPROVE, PERMISSIONS.APPROVALS_REJECT, PERMISSIONS.APPROVALS_CANCEL, PERMISSIONS.APPROVALS_COMMENT, PERMISSIONS.REPORTS_VIEW],
  [ROLES.SELLER]: [PERMISSIONS.CLIENTS_VIEW, PERMISSIONS.CLIENTS_CREATE, PERMISSIONS.CLIENTS_UPDATE, PERMISSIONS.PRODUCTS_VIEW, PERMISSIONS.QUOTES_VIEW, PERMISSIONS.QUOTES_CREATE, PERMISSIONS.QUOTES_UPDATE, PERMISSIONS.QUOTES_CONVERT, PERMISSIONS.ORDERS_VIEW, PERMISSIONS.ORDERS_CREATE, PERMISSIONS.ORDERS_UPDATE, PERMISSIONS.DISCOUNTS_APPLY, PERMISSIONS.APPROVALS_VIEW, PERMISSIONS.APPROVALS_COMMENT],
  [ROLES.CLIENT]: [PERMISSIONS.QUOTES_VIEW, PERMISSIONS.QUOTES_CREATE, PERMISSIONS.ORDERS_VIEW],
  [ROLES.WAREHOUSE]: [PERMISSIONS.PRODUCTS_VIEW, PERMISSIONS.ORDERS_VIEW, PERMISSIONS.DISPATCH_VIEW, PERMISSIONS.DISPATCH_CREATE, PERMISSIONS.DISPATCH_UPDATE],
  [ROLES.LOGISTICS]: [PERMISSIONS.PRODUCTS_VIEW, PERMISSIONS.ORDERS_VIEW, PERMISSIONS.DISPATCH_VIEW, PERMISSIONS.DISPATCH_UPDATE],
} as const satisfies PermissionMap;

export const ROLE_PERMISSIONS: readonly RolePermission[] = Object.entries(ROLE_PERMISSION_MAP).map(([role, permissions]) => ({ role: role as keyof typeof ROLE_PERMISSION_MAP, permissions }));
